version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: tmm_db
    environment:
      POSTGRES_DB: tmm_db
      POSTGRES_USER: tmm_user
      POSTGRES_PASSWORD: tmm_password
    ports:
      - "5432:5432"
    volumes:
      - tmm_data:/var/lib/postgresql/data

volumes:
  tmm_data:
