spring.application.name=un-tmm-service

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/tmm_db
spring.datasource.username=tmm_user
spring.datasource.password=tmm_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

# Pagination defaults
spring.data.web.pageable.default-page-size=20
spring.data.web.pageable.max-page-size=100
